package com.faisal.bkashdemo.rest;

public enum ApiResponseError {
    Brandlist, FeaturedDeviceList, Favlist, HistoryList, SearchResult,
    ErrorType, Forum, PostForum, PostReply, USERPROFILE, SPECIALTY_LIST,
    ConnectionList, Token, UPLOAD_IMAGE, PostImageForum, POST_WITH_IMAGE,
    UPDATE_PROFILE, UPDATE_REPLY_LIST, GET_USER_PROFILE, Product_Details,
    CHECK_FAV, UPDATE_SPECIFIC_FORUM, ALL_CONNECTION, MEDIA, PushAccessToken,
    REGISTRATION_SERVER, GET_UNREAD_MESSAGE, InboxFragment, SIGNUP, INSTANT_PUSH,
    UPLOAD_VIDEO, POST_WITH_ATTACHMENT, DELETE_POST, WRITE_POST, USER_TAG,
    DEVICE_TAG, Offer_Details, Notification, Forum_List, Report_Post, Make_UnFav,
    Make_Fav, CHAT_HISTORY, CHANGE_CONNECTION_STATUS, CHANGE_INVITATION_STATUS,
    CHANGE_STATUS, UNREAD_COUNT, PUT_DEVICE_FORUM, FORUM_DETAILS, DELETE_NOTIFICATION,
    GET_SUGGESTED_USER, GET_SEARCH_CONNECTION, GET_SPECIFIC_POST, UPDATE_SEARCH_HISTORY,
    LOGIN, WebBanner, MEDIA_CHANNEL, Categorylist
}
